---
name: greeter

description: source code for the parent "greeter" action

inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World

outputs:
  time:
    description: When the greeting happened

runs:
  using: node20
  main: index.js
