---
name: greeter

description: source code for the "greeter" action

inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  time:
    description: 'The time we greeted you'

runs:
  using: node20
  main: index.js
