name: greeter

description: prints "Hello World!"

outputs:
  time:
    description: 'The time we greeted you'
    value: ${{ steps.run-action.outputs.time }}

runs:
  using: composite
  steps:
    - name: First, outside action call
      shell: bash
      run: |
        node --version

    - uses: ./../.github/actions/_greeter
      id: run-action

    - name: Last, outside action call
      shell: bash
      run: |
        node --version
        echo "output: ${{ steps.run-action.outputs.time }}"
