name: greeter

description: prints "Hello World!"

outputs:
  time:
    description: 'The time we greeted you'
    value: ${{ steps.run-action.outputs.time }}

runs:
  using: composite
  steps:
    - name: First, outside action call
      shell: bash
      run: |
        node --version

    - name: '[DEBUG]: `pwd`'
      shell: bash
      run: |
        pwd

    - name: Link dynamic dep. Action location to expected
      shell: bash
      env:
        THIS_ACTIONS_PATH: ${{ github.action_path }}
        EXPECTED_ACTIONS_PATH: .github/actions/internal/greeter
      run: |
        expected_actions_dir="$(dirname $EXPECTED_ACTIONS_PATH)"
        mkdir -p "$expected_actions_dir"
        this_actions_dir="$(dirname $THIS_ACTIONS_PATH)"
        ln -fs "$this_actions_dir" "$EXPECTED_ACTIONS_PATH"

    - name: '[DEBUG]: `ls` expected action dir'
      shell: bash
      env:
        EXPECTED_ACTIONS_PATH: .github/actions/internal/greeter
      run: |
        ls "$EXPECTED_ACTIONS_PATH"

    - uses: ./.github/actions/internal/greeter
      id: run-action

    - name: Last, outside action call
      shell: bash
      run: |
        node --version
        echo "output: ${{ steps.run-action.outputs.time }}"
