---
name: greeter

description: 'Give someone a greeting!'

inputs:
  who-to-greet:
    description: Who to greet
    type: string
    required: true

outputs:
  time:
    description: When the greeting happened
    value: ${{ steps.internal-action.outputs.time }}

runs:
  using: composite
  steps:
    - name: Print `node` version at start of action
      shell: bash
      run: |
        node --version

### ==== TO_REPEAT ====
    - name: Set constants for internal action
      shell: bash
      id: constants
      env:
        INTERNAL_ACTION_PATH: ${{ github.action_path }}/internal
        EXPECTED_ACTION_PATH: .github/actions/_internal/greeter
      run: |
        echo "expected-action-path=$EXPECTED_ACTION_PATH" >> "$GITHUB_OUTPUT"
        echo "internal-action-path=$INTERNAL_ACTION_PATH" >> "$GITHUB_OUTPUT"

    - name: Link internal action to expected path
      shell: bash
      env:
        INTERNAL_ACTION_PATH: ${{ steps.constants.outputs.internal-action-path }}
        EXPECTED_ACTION_PATH: ${{ steps.constants.outputs.expected-action-path }}
      run: |
        expected_dir="$(dirname $EXPECTED_ACTION_PATH)"
        mkdir -p "$expected_dir"
        ln -fs "$INTERNAL_ACTION_PATH" "$EXPECTED_ACTION_PATH"

    - name: '[DEBUG]: Print contents of linked path'
      shell: bash
      env:
        EXPECTED_PATH: ${{ steps.constants.outputs.expected-action-path }}
      run: |
        tree -a "$EXPECTED_PATH"

    - uses: ./.github/actions/_internal/greeter
      id: internal-action
      with:
        who-to-greet: ${{ inputs.who-to-greet }}

    - name: '[DEBUG]: Print any outputs from internal action'
      shell: bash
      env:
        OUTPUT: ${{ steps.internal-action.outputs.time }}
      run: |
        echo "output: $OUTPUT"
### ==== / TO_REPEAT ====

    - name: Print `node` version at end of action
      shell: bash
      run: |
        node --version
