name: greeter

description: Greets the caller (wraps `src/greeter` action)

outputs:
  time:
    description: The time you were greeted
    value: ${{ steps.run-action.outputs.time }}

runs:
  using: composite
  steps:
    - name: Print `node` version of runner
      shell: bash
      run: |
        node --version

### ==== TO_REPEAT ====

    - name: Set action constants
      shell: bash
      id: constants
      env:
        INTERNAL_ACTION_PATH: ${{ github.action_path }}/internal
        EXPECTED_ACTION_PATH: .github/actions/internal/greeter
      run: |
        echo "expected-action-path=$EXPECTED_ACTION_PATH" >> "$GITHUB_OUTPUT"
        echo "internal-action-path=$INTERNAL_ACTION_PATH" >> "$GITHUB_OUTPUT"

    - name: Link dependent action to expected path
      shell: bash
      env:
        ACTION_PATH: ${{ steps.constants.outputs.internal-action-path }}
        EXPECTED_PATH: ${{ steps.constants.outputs.expected-action-path }}
      run: |
        expected_dir="$(dirname $EXPECTED_PATH)"
        mkdir -p "$expected_dir"
        ln -fs "$ACTION_PATH" "$EXPECTED_PATH"

    - name: '[DEBUG]: Print where the action-to-call should be'
      shell: bash
      env:
        EXPECTED_PATH: ${{ steps.constants.outputs.expected-action-path }}
      run: |
        tree -a "$EXPECTED_PATH"

    - uses: ./.github/actions/internal/greeter
      id: run-action

    - name: Print `node` version of runner after calling action
      shell: bash
      run: |
        node --version

### ==== / TO_REPEAT ====

    - name: Print output from called action
      shell: bash
      env:
        OUTPUT: ${{ steps.run-action.outputs.time }}
      run: |
        echo "output: $OUTPUT"
