---
name: print-node-version

description: "Print the version of NodeJS that's running this action!"

runs:
  using: composite
  steps:
    - name: Print `node` version at start of action
      shell: bash
      run: |
        node --version

### ==== TO_REPEAT ====
    - name: Link internal action to expected path
      shell: bash
      env:
        INTERNAL_ACTION_PATH: ${{ github.action_path }}/internal
        EXPECTED_ACTION_PATH: .github/actions/_internal/print-version
      run: |
        expected_dir="$(dirname $EXPECTED_ACTION_PATH)"
        mkdir -p "$expected_dir"
        ln -fs "$INTERNAL_ACTION_PATH" "$EXPECTED_ACTION_PATH"

    - uses: ./.github/actions/_internal/print-version
      id: internal-action

### ==== / TO_REPEAT ====
    - name: Print `node` version at end of action
      shell: bash
      run: |
        node --version
