name: print-version

description: prints the Node version, wrapped

runs:
  using: composite
  steps:
    - name: First, outside action call
      shell: bash
      run: |
        node --version

    - uses: ./../.github/actions/_print-version

    - name: Last, outside action call
      shell: bash
      run: |
        node --version
