name: print-version

description: prints the Node version, wrapped

runs:
  using: composite
  steps:
    - name: First, outside action call
      shell: bash
      run: |
        node --version

    - uses: faubion-hbo/javascript-actions/.github/actions/_print-version@main

    - name: Last, outside action call
      shell: bash
      run: |
        node --version
